### ISSUE TITLE
A Volume bar to increase or decrease the volume of the song

### ISSUE THREAD

**Issue by VivekChatterjee** [samratghosh291/Musicia-music-player#10]
- Create a volume bar
- On selecting different portions of volume bar, volume should increase or decrease just like in youtube

**Comment by VivekChatterjee** [comment]
Hi @samratghosh291 , please assign me this issue, I would like to work on this.

**Comment by samratghosh291** [comment]
Thank You!! Vivek for your interest!!.. Happy Coding!!
