### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia-music-player#3]
The README file of our project is essential for providing information about the project, how to use it, and how to contribute effectively. However, it may be outdated, lacking crucial information, or needing a fresh update to reflect recent changes.

**Comment by samratghosh291** [comment]
@AniruddhaGawali Thank you for your interest!!...
Happy Coding!!

**Comment by AniruddhaGawali** [comment]
Can you tell me which things are need to be added so that i can update readme file accounting to it

**Comment by samratghosh291** [comment]
@AniruddhaGawali  design the Readme.md file so that it can clearly describe about the project.
Certainly, here are the basic points to cover in a good README.md:

1. Title and Description
2. Table of Contents
3. Installation
4. Usage
7. Contributing
Contact Information
Demo or Screenshots
This is the basic features inside a Readme.md should cover.  But you can add by yourself many things is already covered...decorate and butify it.

**Comment by samratghosh291** [comment]
@AniruddhaGawali you just added a screenshot but messed up all alignment. 
this is your first time but make sure next time you would no do this.
