### ISSUE TITLE
Make a Navbar

### ISSUE THREAD

**Issue by samratghosh291** [samratghosh291/Musicia-music-player#4]
A navbar should have these features

- home
- my songs
- liked songs
- my account (pictorial)( at rightmost )
- logout

**Comment by AniruddhaGawali** [comment]
i can do that till tomorrow can you assign it to me

**Comment by 17rawat** [comment]
Hey Sam, can I continue on this?

**Comment by CoderRedwing** [comment]
kindly assign it to me

**Comment by samratghosh291** [comment]
@AniruddhaGawali OK go for it ❤️

**Comment by samratghosh291** [comment]
@17rawat @CoderRedwing you can raise another issue and then asking for assigning 👍
